include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: info
    use_build_context_synchronously: warning

linter:
  rules:
    # --- 스타일 및 가독성 ---
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # --- 코드 품질 및 버그 예방 ---
    always_declare_return_types: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    cancel_subscriptions: true
    close_sinks: true
    
    # --- 추가 권장 규칙 ---
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
